version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.6.3
  build:
    context: .
    dockerfile: Dockerfile

  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_ENABLED: 'True'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./airflow/logs:/opt/airflow/logs1
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  webserver:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    command: scheduler

volumes:
  postgres-db-volume:
